using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Giger.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // This will be auto-generated by EF Core when you run: dotnet ef migrations add InitialCreate
            // For now, the database will be created automatically based on the DbContext model
            // when the application starts with automatic migrations enabled
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Rollback logic
        }
    }
}
