using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Giger.Services;

#nullable disable

namespace Giger.Migrations
{
    [DbContext(typeof(GigerDbContext))]
    partial class GigerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            // This will be auto-generated by EF Core
            // The model snapshot is created when you run: dotnet ef migrations add InitialCreate
        }
    }
}
