export enum Factions {
    gunners = 'gunners',
    spanks_and_cuddles = 'spanks_and_cuddles',
    rabbids = 'rabbids',
    pawnshop_24_7 = 'pawnshop_24_7',
    o_m_g = 'o_m_g',
    humanists = 'humanists',
    metamorphosis = 'metamorphosis',
    t_f_a = 't_f_a',
    double_d = 'double_d',
    esthetics = 'esthetics',
    q_e_t_s = 'q_e_t_s',
    Synth_Pulse = 'Synth_Pulse',
    Nu_Yu = 'Nu_Yu',
    transhuman = 'transhuman',
    hi_tech = 'hi_tech',
    a_spot = 'a_spot',
    beholder = 'beholder',
    anarchy = 'anarchy',
    nomads = 'nomads',
    foundation = 'foundation',
    shaman = 'shaman',
    head_hunters = 'head_hunters',
    reapers = 'reapers',
    loaded_chamber = 'loaded_chamber',
    byte_bar = 'byte_bar',
    takayama_official = 'takayama_official',
    social_net = 'social_net',
    contech_regional = 'contech_regional'
}

export const FactionsFullNames = new Map<Factions, string>([
    [Factions.gunners, 'Gunners'],
    [Factions.spanks_and_cuddles, 'Spanks&Cuddles'],
    [Factions.rabbids, 'Rabbids'],
    [Factions.pawnshop_24_7, 'Pawnshop 24/7'],
    [Factions.o_m_g, 'Omni Municipal Guard'],
    [Factions.humanists, 'Humanists'],
    [Factions.metamorphosis, 'Metamorphosis'],
    [Factions.takayama_official, 'Takayama Finance Agency'],
    [Factions.double_d, 'DoubleD'],
    [Factions.esthetics, 'Esthetics'],
    [Factions.q_e_t_s, 'Quantum-Elite Talent Syndicate'],
    [Factions.Synth_Pulse, 'SynthPulse'],
    [Factions.Nu_Yu, 'NuYu'],
    [Factions.transhuman, 'Transcenders'],
    [Factions.hi_tech, 'Hi-Tech Clinic'],
    [Factions.a_spot, 'aSpot'],
    [Factions.beholder, 'Beholder'],
    [Factions.anarchy, 'Anarchists'],
    [Factions.nomads, 'Nomads'],
    [Factions.foundation, 'Foundation'],
    [Factions.shaman, 'Shamans'],
    [Factions.head_hunters, 'Head hunters'],
    [Factions.reapers, 'Reapers'],
    [Factions.loaded_chamber, 'The Loaded Chamber'],
    [Factions.byte_bar, 'Byte Bar'],
    [Factions.takayama_official, 'Takayama'],
    [Factions.social_net, 'Social Network'],
    [Factions.contech_regional, 'ConTech']
]);
