{{- $initArchivePath := .Values.database.initArchivePath | default "files/postgres-init.tar.xz" -}}
{{- $hasInitArchive := gt (len (.Files.Glob $initArchivePath)) 0 -}}
{{- if and .Values.database.initFromConfigMap $hasInitArchive }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gig3r.postgres.init.configmap" . }}
binaryData:
  postgres-init.tar.xz: {{ .Files.Get $initArchivePath | b64enc | quote }}
{{- end }}