{{- if .Values.pgadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gig3r.pgadmin.app" . }}
spec:
  replicas: {{ .Values.pgadmin.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "gig3r.pgadmin.app" . }}
  template:
    metadata:
      labels:
        app: {{ include "gig3r.pgadmin.app" . }}
        randstr: {{ randAlphaNum 20 }}
    spec:
      {{- if .Values.dockerconfigjson }}
      imagePullSecrets:
      - name: regcred
      {{- end }}
      containers:
      - image: {{ include "gig3r.pgadmin.image" . }}
        name: {{ include "gig3r.pgadmin.app" . }}
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: gig3r-secret
              key: PGADMIN_DEFAULT_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gig3r-secret
              key: PGADMIN_DEFAULT_PASSWORD
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: "False"
        - name: PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED
          value: "False"
      restartPolicy: Always
{{- end }}

---
