---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gig3r.frontend.app" . }}
spec:
  replicas: {{ .Values.frontend.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "gig3r.frontend.app" . }}
  template:
    metadata:
      labels:
        app: {{ include "gig3r.frontend.app" . }}
        randstr: {{ randAlphaNum 20 }}
    spec:
      {{- if .Values.dockerconfigjson }}
      imagePullSecrets:
      - name: regcred
      {{- end }}
      containers:
      - image: {{ include "gig3r.frontend.image" . }}
        name: {{ include "gig3r.frontend.app" . }}
        ports:
        - containerPort: 8080
          protocol: TCP
      restartPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gig3r.backend.app" . }}
spec:
  replicas: {{ .Values.backend.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "gig3r.backend.app" . }}
  template:
    metadata:
      labels:
        app: {{ include "gig3r.backend.app" . }}
        randstr: {{ randAlphaNum 20 }}
    spec:
      {{- if .Values.dockerconfigjson }}
      imagePullSecrets:
      - name: regcred
      {{- end }}
      containers:
      - image: {{ include "gig3r.backend.image" . }}
        name: {{ include "gig3r.backend.app" . }}
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DOTNET_USE_POLLING_FILE_WATCHER
          value: "1"
        - name: GigerDB__Host
          value: {{ include "gig3r.postgres.app" . }}
        - name: GigerDB__Port
          value: "5432"
        - name: GigerDB__Username
          valueFrom:
            secretKeyRef:
              name: gig3r-secret
              key: GIGER_DB_USERNAME
        - name: GigerDB__Password
          valueFrom:
            secretKeyRef:
              name: gig3r-secret
              key: GIGER_DB_PASSWORD
        - name: GigerDB__DatabaseName
          valueFrom:
            secretKeyRef:
              name: gig3r-secret
              key: GIGER_DB_NAME
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ include "gig3r.backend.environment" .}}
      restartPolicy: Always

---
