{{- if (or (eq true .Values.mongo.persistent) (eq "app" .Values.environment )) }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "gig3r.mongodb.pv" . }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
{{- end -}}