---
#docker registry auth secret
{{- if .Values.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson | quote }}
{{- end }}
