---
apiVersion: v1
kind: Secret
metadata:
  name: gig3r-secret
  annotations:
    app.kubernetes.io/managed-by: "Helm"
data:
  DB_PASSWORD: "{{ include "gig3r.database.password" (dict "Namespace" .Release.Namespace ) }}"
  backend_config.json: >-
{{ include "gig3r.backend.config" (dict "Namespace" .Release.Namespace ) | indent 4 }}

