---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-express-secret
data:
  ME_CONFIG_BASICAUTH_USERNAME: {{ .Values.mongoexpress.user | b64enc | quote }}
  ME_CONFIG_BASICAUTH_PASSWORD: {{ .Values.mongoexpress.password | b64enc | quote }}

---

#docker registry auth secret
apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson | quote }}
