"""empty message

Revision ID: c6a51fed6660
Revises: 2c2d22ea1c8b
Create Date: 2023-11-13 12:11:25.659991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a51fed6660'
down_revision = '2c2d22ea1c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phash_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'authorization', ['phash_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('phash_id')

    # ### end Alembic commands ###
