name: Deploy Helm Chart
on:
  workflow_call:
    inputs:
      GITHUB_RUNNER_NAME:
        type: string
        required: false
        default: "microk8s-runner-1"
      BASE_URL:
        type: string
        required: false
        default: "gig3r.com"
      HELM_ENVIRONMENT:
        type: string
        required: false
      HELM_FRONTEND_IMAGE:
        type: string
        required: false
        default: mivalsten/gig3r-frontend
      HELM_FRONTEND_TAG:
        type: string
        required: true
      HELM_BACKEND_IMAGE:
        type: string
        required: false
        default: mivalsten/gig3r-backend
      HELM_BACKEND_TAG:
        type: string
        required: true
      HELM_DATABASE_TAG:
        type: string
        required: true
      HELM_DATABASE_IMAGE:
        type: string
        required: false
        default: mivalsten/gig3r-mongo
    secrets:
      KUBECONFIG:
        required: true
      DATA_SSH_KEY:
        required: true
    outputs:
      address:
        description: "address of deployed environment"
        value: ${{ jobs.deploy_helm_chart.outputs.address }}
env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.IMAGE_NAME }}

jobs:
  deploy_helm_chart:
    runs-on: ${{ inputs.GITHUB_RUNNER_NAME }}
    outputs:
      address: ${{ steps.address.outputs.address }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DATA_SSH_KEY }}
          submodules: recursive

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        with:
          prefix: CI_

      - name: Deploy
        uses: 'WyriHaximus/github-action-helm3@v3'
        with:
          exec: |
            helm upgrade --install \
            gig3r-${{ env.HELM_ENVIRONMENT }} \
            ./chart/gig3r \
            --wait \
            --atomic \
            --namespace=${{ env.HELM_ENVIRONMENT }} \
            --create-namespace \
            --set environment=${{ env.HELM_ENVIRONMENT }} \
            --set base_url=${{ inputs.BASE_URL }} \
            --set dockerconfigjson=${{ secrets.REGCRED }} \
            --set frontend.image=${{ inputs.HELM_FRONTEND_IMAGE }} \
            --set frontend.tag=${{ env.HELM_FRONTEND_TAG }} \
            --set backend.image=${{ inputs.HELM_BACKEND_IMAGE }} \
            --set backend.tag=${{ env.HELM_BACKEND_TAG }} \
            --set database.name=${{ env.HELM_ENVIRONMENT }} \
            --set database.user=${{ env.HELM_ENVIRONMENT }} \
            --set database.image=${{ inputs.HELM_DATABASE_IMAGE }} \
            --set database.tag=${{ env.HELM_DATABASE_TAG }} \
            --set mongoexpress.user=${{ secrets.ME_USER }} \
            --set mongoexpress.password=${{ secrets.ME_PASSWORD }} \
            --set mongo.persistent=${{ env.PERSISTENT }}
                    
          kubeconfig: ${{ secrets.KUBECONFIG }}
          overrule_existing_kubeconfig: true
        env:
          HELM_FRONTEND_TAG: ${{ inputs.HELM_FRONTEND_TAG }} #${{ inputs.IMAGE_TAG && inputs.IMAGE_TAG || env.CI_GITHUB_REF_NAME_SLUG_URL }}
          HELM_BACKEND_TAG: ${{ inputs.HELM_BACKEND_TAG }} #${{ inputs.IMAGE_TAG && inputs.IMAGE_TAG || env.CI_GITHUB_REF_NAME_SLUG_URL }}
          HELM_DATABASE_TAG: ${{ inputs.HELM_DATABASE_TAG }} #${{ inputs.IMAGE_TAG && inputs.IMAGE_TAG || env.CI_GITHUB_REF_NAME_SLUG_URL }}
          HELM_ENVIRONMENT: ${{ inputs.HELM_ENVIRONMENT != '' && inputs.HELM_ENVIRONMENT || env.CI_GITHUB_REF_NAME_SLUG_URL }}
          PERSISTENT: ${{ contains(github.event.pull_request.labels.*.name, 'persistent-storage')) }}

      - name: output address
        id: address
        run: echo "address=${{ inputs.HELM_ENVIRONMENT != '' && inputs.HELM_ENVIRONMENT || env.CI_GITHUB_REF_NAME_SLUG_URL }}.${{ inputs.BASE_URL }}" >> $GITHUB_OUTPUT