name: Deploy Helm Chart
on:
  workflow_call:
    inputs:
      GITHUB_RUNNER_NAME:
        type: string
        required: false
        default: "microk8s-runner-1"
      HELM_ENVIRONMENT:
        type: string
        required: true
      HELM_FRONTEND_IMAGE:
        type: string
        required: false
        default: mivalsten/gig3r-frontend
      HELM_FRONTEND_TAG:
        type: string
        required: true
    secrets:
      KUBECONFIG:
        required: true
env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.IMAGE_NAME }}
  

jobs:
  deploy-helm-chart:
    runs-on: ${{ inputs.GITHUB_RUNNER_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set variables
        run: |
          
      - name: 'Deploy'
        uses: 'deliverybot/helm@v1'
        with:
          release: gig3r-${{ inputs.HELM_ENVIRONMENT }}
          namespace: ${{ inputs.HELM_ENVIRONMENT }}
          chart: './chart/gig3r'
          values: |
            environment: ${{ inputs.HELM_ENVIRONMENT }}
            base-url: gig3r.com
            frontend:
              image: ${{ inputs.HELM_FRONTEND_IMAGE }}
              tag: ${{ env.HELM_FRONTEND_TAG }}
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
          HELM_FRONTEND_TAG: ${{ inputs.HELM_FFRONTEND_TAG }} #${{ inputs.IMAGE_TAG && inputs.IMAGE_TAG || env.CI_GITHUB_REF_NAME_SLUG_URL }}
