name: Deploy Helm Chart
on:
  workflow_call:
    inputs:
      GITHUB_RUNNER_NAME:
        type: string
        required: false
        default: "microk8s-runner-1"
      HELM_ENVIRONMENT:
        type: string
        required: true
      HELM_FRONTEND_IMAGE:
        type: string
        required: false
        default: mivalsten/gig3r-frontend
      HELM_FRONTEND_TAG:
        type: string
        required: true
    secrets:
      KUBECONFIG:
        required: true
env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.IMAGE_NAME }}
  

jobs:
  deploy-helm-chart:
    runs-on: ${{ inputs.GITHUB_RUNNER_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set variables
        run: |
          
      - name: 'Deploy'
        uses: 'WyriHaximus/github-action-helm3@v3'
        with:
          exec: |
            helm upgrade --install \
            gig3r-dev \
            ./chart/gig3r \
            --wait \
            --atomic \
            --namespace=${{ inputs.HELM_ENVIRONMENT }} \
            --create-namespace \
            --set environment=${{ inputs.HELM_ENVIRONMENT }} \
            --set base_url=gig3r.com \
            --set frontend.image=${{ inputs.HELM_FRONTEND_IMAGE }} \
            --set frontend.tag=${{ env.HELM_FRONTEND_TAG }} \
            --set database.name=${{ inputs.HELM_ENVIRONMENT }} \
            --set database.user=${{ inputs.HELM_ENVIRONMENT }} \
            --set database.password=test \
            --set database.admin.user=postgres \
            --set database.admin.password=${{ secrets.POSTGRES_PASSWORD }}
                    
          kubeconfig: ${{ secrets.KUBECONFIG }}
          overrule_existing_kubeconfig: true
        env:
          HELM_FRONTEND_TAG: ${{ inputs.HELM_FRONTEND_TAG }} #${{ inputs.IMAGE_TAG && inputs.IMAGE_TAG || env.CI_GITHUB_REF_NAME_SLUG_URL }}
