name: Deploy Helm Chart
on:
  workflow_call:
    inputs:
      GITHUB_RUNNER_NAME:
        type: string
        required: false
        default: "microk8s-runner-1"
      HELM_ENVIRONMENT:
        type: string
        required: false
      HELM_FRONTEND_IMAGE:
        type: string
        required: false
        default: mivalsten/gig3r-frontend
      HELM_FRONTEND_TAG:
        type: string
        required: true
      HELM_BACKEND_IMAGE:
        type: string
        required: false
        default: mivalsten/gig3r-backend
      HELM_BACKEND_TAG:
        type: string
        required: true
    secrets:
      KUBECONFIG:
        required: true
env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.IMAGE_NAME }}
  

jobs:
  deploy-helm-chart:
    runs-on: ${{ inputs.GITHUB_RUNNER_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        with:
          prefix: CI_

      - name: install additional packages
        run: |
          sudo apt update
          sudo apt install -y curl
      - name: 'Deploy'
        uses: 'WyriHaximus/github-action-helm3@v3'
        with:
          exec: |
            helm upgrade --install \
            gig3r-${{ env.HELM_ENVIRONMENT }} \
            ./chart/gig3r \
            --wait \
            --atomic \
            --namespace=${{ env.HELM_ENVIRONMENT }} \
            --create-namespace \
            --set environment=${{ env.HELM_ENVIRONMENT }} \
            --set base_url=gig3r.com \
            --set frontend.image=${{ inputs.HELM_FRONTEND_IMAGE }} \
            --set frontend.tag=${{ env.HELM_FRONTEND_TAG }} \
            --set backend.image=${{ inputs.HELM_BACKEND_IMAGE }} \
            --set backend.tag=${{ env.HELM_BACKEND_TAG }} \
            --set database.name=${{ env.HELM_ENVIRONMENT }} \
            --set database.user=${{ env.HELM_ENVIRONMENT }} \
            --set database.admin.user=postgres \
            --set database.admin.password=${{ secrets.POSTGRES_PASSWORD }}
                    
          kubeconfig: ${{ secrets.KUBECONFIG }}
          overrule_existing_kubeconfig: true
        env:
          HELM_FRONTEND_TAG: ${{ inputs.HELM_FRONTEND_TAG }} #${{ inputs.IMAGE_TAG && inputs.IMAGE_TAG || env.CI_GITHUB_REF_NAME_SLUG_URL }}
          HELM_BACKEND_TAG: ${{ inputs.HELM_BACKEND_TAG }} #${{ inputs.IMAGE_TAG && inputs.IMAGE_TAG || env.CI_GITHUB_REF_NAME_SLUG_URL }}
          HELM_ENVIRONMENT: ${{ inputs.HELM_ENVIRONMENT != '' && inputs.HELM_ENVIRONMENT || env.CI_GITHUB_REF_NAME_SLUG_URL }}
